### ISSUE TITLE
matrix24x25magmalavathing

### ISSUE THREAD

**Issue by mariomeraz** [doctorpartlow/workingfastledanimations#1]
Hello!

Change Color Order to RGB and my lava is blue and red, with the original configuration it is green and pink
![IMG_0593](https://user-images.githubusercontent.com/14825814/196771700-28a3d524-2b35-4808-8423-abab40b8dd78.jpg)

**Comment by doctorpartlow** [comment]
in the code go to this section
`bool EffectMagma::run() {
  fadeToBlackBy(leds, NUM_LEDS, 25);

  for (uint8_t i = 0; i < ObjectNUM; i++) {
    LeapersMove_leaper(i);
    drawPixelXYF(trackingObjectPosX[i], trackingObjectPosY[i], ColorFromPalette(CopperFireColors_p, trackingObjectHue[i], 255));
  }

  for (uint8_t i = 0; i < WIDTH; i++) {
    for (uint8_t j = 0; j < HEIGHT; j++) {
      leds[XY(i, HEIGHT-1 - j)] += ColorFromPalette(RubidiumFireColors_p, qsub8(inoise8(i * deltaValue, (j + ff_y + random8(2)) * deltaHue, ff_z), shiftHue[j]), 255U);
    }
  }
`
where it says RubidiumFireColors_p change that to LavaColors_p and the one above that change it to the same. that should make the colors look like lava.  I had those set to weird colors. the ColorFromPalette function controls what colors are displayed. let me know if you're able to get it working.

**Comment by mariomeraz** [comment]
excellent now if it works, and I see that there are more color combinations, it's great

Thks
